export const DOG_BREEDS = [
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "American Bulldog",
  "American Cocker Spaniel",
  "Australian Shepherd",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Bearded Collie",
  "Bedlington Terrier",
  "Belgian Shepherd",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Bloodhound",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier des Flandres",
  "Boxer",
  "Boykin Spaniel",
  "Bull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Cane Corso",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chinese Crested",
  "Chow Chow",
  "Clumber Spaniel",
  "Cockapoo",
  "Cocker Spaniel",
  "Collie",
  "Corgi (Pembroke Welsh)",
  "Corgi (Cardigan Welsh)",
  "Dachshund",
  "Dalmatian",
  "Dobermann",
  "English Setter",
  "English Springer Spaniel",
  "Flat-Coated Retriever",
  "French Bulldog",
  "German Pointer",
  "German Shepherd",
  "German Shorthaired Pointer",
  "Golden Retriever",
  "Gordon Setter",
  "Great Dane",
  "Greyhound",
  "Hungarian Vizsla",
  "Irish Setter",
  "Irish Terrier",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Japanese Akita",
  "Japanese Chin",
  "Keeshond",
  "Kerry Blue Terrier",
  "King Charles Spaniel",
  "Labradoodle",
  "Labrador Retriever",
  "Lakeland Terrier",
  "Lhasa Apso",
  "Lurcher",
  "Maltese",
  "Mastiff",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Newfoundland",
  "Norfolk Terrier",
  "Norwich Terrier",
  "Old English Sheepdog",
  "Papillon",
  "Patterdale Terrier",
  "Pekingese",
  "Pointer",
  "Pomeranian",
  "Poodle (Standard)",
  "Poodle (Miniature)",
  "Poodle (Toy)",
  "Portuguese Water Dog",
  "Pug",
  "Puggle",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Saint Bernard",
  "Samoyed",
  "Schnauzer",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Shar Pei",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Siberian Husky",
  "Springer Spaniel",
  "Staffordshire Bull Terrier",
  "St. Bernard",
  "Vizsla",
  "Weimaraner",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Whippet",
  "Wire Fox Terrier",
  "Yorkshire Terrier",
  "Crossbreed / Mixed breed",
] as const

export const OTHER_BREED_VALUE = "__other__"
